### ISSUE TITLE
npm version is not updated

### ISSUE THREAD

**Issue by Frank3K** [hrajchert/angular-screenfull#19]
The release on npm is not updated. It is still at v0.1.0, as can be seen on [npmjs](https://www.npmjs.com/package/angular-screenfull).

According to [the npm docs](https://docs.npmjs.com/getting-started/publishing-npm-packages), you should run `npm publish` to update the package:

```
Updating the package

...

After updating the version number, you can npm publish again.
```

**Comment by hrajchert** [comment]
Thanks frank! In the following days I'll upgrade the package skiping this version and making sure it works well in npm and deprecating bower, updating the docs, etc

**Comment by Frank3K** [comment]
Small bump :)

**Comment by Frank3K** [comment]
Another minor bump :)

**Comment by johnou** [comment]
@hrajchert ping

**Comment by hrajchert** [comment]
Hi all, so sorry about the delay, I'm having trouble mantaining this as all the stack has gotten a little outdated. For example, I had to remove the dust on a Grunt project I used, to test things work fine.

A lot of things changed since I originally started this project, so if you want to keep it up to date, for example making sure it works with angular 1.6/7 and webpack, PR's are always welcomed.

Right now I bumped the version to 0.2.0, using the screenfull dependency 3.3.0
